# Generated by Django 5.2.3 on 2025-06-27 11:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChatSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=100, unique=True, verbose_name='Session ID')),
                ('user_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='User ID')),
                ('language', models.CharField(choices=[('fr', 'Français'), ('rn', 'Ikirundi'), ('en', 'English')], default='fr', max_length=2, verbose_name='Language')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Chat Session',
                'verbose_name_plural': 'Chat Sessions',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.JSONField(help_text="Name in multiple languages: {'fr': '...', 'rn': '...', 'en': '...'}", verbose_name='Service Name')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
                ('description', models.JSONField(help_text='Description in multiple languages', verbose_name='Description')),
                ('required_documents', models.JSONField(help_text='List of required documents', verbose_name='Required Documents')),
                ('eligibility', models.JSONField(help_text='Eligibility criteria in multiple languages', verbose_name='Eligibility')),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(verbose_name='Message')),
                ('is_user', models.BooleanField(default=True, verbose_name='Is User Message')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chatbot.chatsession', verbose_name='Session')),
            ],
            options={
                'verbose_name': 'Chat Message',
                'verbose_name_plural': 'Chat Messages',
            },
        ),
    ]
